spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  data:
    redis:
      host: localhost
      port: 6379

  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfigurationV2


jwt:
  secret:
    key: ${JWT_SECRET_KEY:c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLXNlY3JldC1rZXktMjAyMw==}
  access-token-expiry: 15m
  refresh-token-expiry: 7d

app:
  cors:
    allowed-origins: "*"
